steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/aren-ai/arenai-repo/aren-ai-api', '.']

images:
- 'us-central1-docker.pkg.dev/aren-ai/arenai-repo/aren-ai-api'

options:
  logging: CLOUD_LOGGING_ONLY
